# **Tarea de Numpy**

Este notebook es el de los ejercicios >:)

In [4]:
!pip install numpy
import numpy as np

# Probando si si jala el numpy
my_arreglow = np.array([1, 2, 3, 4, 5])

print(my_arreglow)
print(np.mean(my_arreglow))


[1 2 3 4 5]
3.0


## Ejercicios de refuerzo

💙💻 **Jessica Stephanie Garcia Monjaraz** 💻💙

### **Ejercicio 1 - Crear un array de ceros:**
Crea un array de tamaño (3, 4) lleno de ceros.

In [23]:
# Solución (:

arr_ceros = np.zeros((3, 4))
print("Arreglo de ceros:\n", arr_ceros)

Arreglo de ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### **Ejercicio 2-  Suma de elementos:**
   Dado el array [1, 2, 3, 4, 5], calcula la suma de todos sus elementos usando NumPy.

In [8]:
# Solucion :)

array_elemento = np.array([1, 2, 3, 4, 5])
print("La suma de elementos es:", np.sum(array_elemento))

La suma de elementos es: 15


### **Ejercicio 3 - Encontrar el máximo y mínimo:**
Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.

In [13]:
array = np.array([10, 20, 30, 40, 50])

# Solución:)

print("El valor minimo del arreglo es:", np.min(array))
print("El valor maximo del arreglo es:", np.max(array))

El valor minimo del arreglo es: 10
El valor maximo del arreglo es: 50


### **Ejercicio 4 - Encontrar el máximo y mínimo:**
 Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.


In [12]:
# Solución:)

array = np.array([10, 20, 30, 40, 50])

print("El valor minimo del arreglo es:", np.min(array))
print("El valor maximo del arreglo es:", np.max(array))


El valor minimo del arreglo es: 10
El valor maximo del arreglo es: 50


### **Ejercicio 5 - Generar números aleatorios:**
  Genera un array de 5 números aleatorios entre 0 y 1.

In [7]:
# Solución:)
  
array_aleatorio = np.random.rand(5)
# Entre 0 y 1 -> La función np.random.rand() genera números aleatorios 
# con distribución uniforme en el intervalo [0.0, 1.0). Este intervalo es el comportamiento por defecto,
# por lo tanto no es necesario declarar explícitamente los límites.
print("Array de 5 números aleatorios:\n",array_aleatorio)

Array de 5 números aleatorios:
 [0.85403801 0.56177581 0.28487894 0.82368765 0.06570616]


### **Ejercicio 6 - Promedio de un array:**
Dado el array [5, 10, 15, 20, 25], calcula su promedio usando NumPy.

In [6]:
#Solucion:)

array_prom = np.array([5, 10, 15, 20, 25])
print("El promedio del arreglo es:", np.mean(array_prom))

El promedio del arreglo es: 15.0


### **Ejercicio 7 - Concatenar dos arrays**
Dados los arrays A = [1, 2, 3] y B = [4, 5, 6], concaténalos en un solo array.

In [9]:
#Solucion:)

array_uno = np.array ([1, 2, 3])
array_dos = np.array ([4, 5, 6])
array_con = np.concatenate((array_uno, array_dos))
print("Arreglo concatenado:\n", array_con)
# o reduciendo en el mismo print
print("\nArreglo concatenado:\n", np.concatenate((array_uno, array_dos)))

Arreglo concatenado:
 [1 2 3 4 5 6]

Arreglo concatenado:
 [1 2 3 4 5 6]


### **Ejercicio 8 - Reshape de un Array**
Dado el array [1, 2, 3, 4, 5, 6], cámbialo a una matriz de 2x3.

In [17]:
#Solución:)

array_resh = np.array([1, 2, 3, 4, 5, 6])
array_resh = array_resh.reshape(2, 3)
print("El arreglo reestructurado es:\n", array_resh)
# o reduciendo en el mismo print
print("\nArreglo reestructurado:\n", np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3))

El arreglo reestructurado es:
 [[1 2 3]
 [4 5 6]]

Arreglo reestructurado:
 [[1 2 3]
 [4 5 6]]


### **Ejercicio 9 - Producto punto (dot product):**
Dados dos arrays A = [1, 2, 3] y B = [4, 5, 6], calcula su producto punto

In [20]:
#Solución:)

array_a= np.array([1, 2, 3])
array_b= np.array([4, 5, 6])
array_pp = np.dot(array_a, array_b)
print("El producto punto es:", array_pp)

# en un solo print
print("\nEl producto punto es:", np.dot(array_a, array_b))

El producto punto es: 32

El producto punto es: 32


### **Ejercicio 10 - Reorganizar un array:**
Dado el array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], conviértelo en una matriz (2, 5).

In [24]:
#Solución:)

array_reorganized = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array_matriz = array_reorganized.reshape(2, 5)
print("El arreglo reorganizado es:\n", array_matriz)


El arreglo reorganizado es:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### **Ejercicio extra - Encontrar el *k*-ésimo elemento más pequeño en un array**
Dado arr = np.array([9, 3, 6, 2, 1, 7]), encuentra el 3er elemento más pequeño sin ordenar el array completo.

**Pista solución 1**: Se puede hacer con un método de Numpy

**Pista solución 2**: El código se hace más complicado, pero se puede resolver con ciclos iterativos.

In [27]:
#Solucion :o
arr = np.array([9, 3, 6, 2, 1, 7])


k = 3 # para el 3er elemento más pequeño -> index 2

# np.partition para reorganizar el array de manera parcial
# Esto pone los k elementos más pequeños en las primeras posiciones, pero no los ordena por completo.
# buscamos el k-1 elemento (por el index)
resultado = np.partition(arr, k-1)
print("Arreglo después de la partición:", resultado) # solo acomoda los k elementos más pequeños al inicio
k_esimo = resultado[k - 1]
print(f"El {k}-ésimo elemento más pequeño es:", k_esimo) # imprimo el resultado usando un f-string
# El prefijo 'f' es para indicar que es un f-string y asi puedo insertar directamente variables dentro 
# del texto usando llaves {}


Arreglo después de la partición: [1 2 3 6 9 7]
El 3-ésimo elemento más pequeño es: 3


## **Ejercicios aplicados**

### **Ejercicio: Cálculo de ROI (Retorno de Inversión)**
Dadas las inversiones ([1000, 1500, 2000]) y sus retornos ([1200, 1650, 1800]), calcula el ROI porcentual para cada caso.

*(Fórmula: ROI = (retorno - inversión) / inversión * 100)*

In [33]:
# Solucion del ROIROIROIROIORIORI

inversiones = np.array([1000, 1500, 2000]) #arreglo de inversiones
retornos = np.array([1200, 1650, 1800]) #arreglo de retornos

#  ROI porcentual para cada inversión
roi = ((retornos - inversiones) / inversiones) * 100

# Recorrer los arreglos segun el numero de inversiones
# len para saber el tamaño del arreglo y el range para recorrerlo
for i in range(len(inversiones)):
    print(f"Para una inversión de ${inversiones[i]} y un retorno de ${retornos[i]}, el ROI es: {roi[i]:.2f}%")


Para una inversión de $1000 y un retorno de $1200, el ROI es: 20.00%
Para una inversión de $1500 y un retorno de $1650, el ROI es: 10.00%
Para una inversión de $2000 y un retorno de $1800, el ROI es: -10.00%


### **Ejercicio: Normalización de Datos**
Tienes un dataset de precios de productos (en USD): [250, 320, 150, 500, 210]. Normaliza los valores al rango [0, 1] para compararlos en una escala común.

**Formulita de la normalización**: (x - min) / (max - min): Para una escala valores entre 0 y 1.

In [41]:
precios = np.array([250, 320, 150, 500, 210])

min_precio = np.min(precios)
max_precio = np.max(precios)


precios_normalizados = (precios - min_precio) / (max_precio - min_precio)

print("Precios originales:", precios)
print("Precios normalizados en el rango de [0, 1]:\n", np.round(precios_normalizados, 3))


Precios originales: [250 320 150 500 210]
Precios normalizados en el rango de [0, 1]:
 [0.286 0.486 0.    1.    0.171]


### **Ejercicio: Filtrado de Datos**
En un array de ventas diarias ([1200, 0, 750, 2400, 0, 1800]), reemplaza los ceros (días sin ventas) por el promedio de los días con ventas.

In [ ]:
array_ventas = np.array([1200, 0, 750, 2400, 0, 1800])

promedio_ventas = np.mean(array_ventas[array_ventas != 0]) # se calcula el promedio de los elementos
# que no sean cero
array_ventas[array_ventas == 0] = promedio_ventas # si el elemento es cero lo reemplaza por el promedio
print("Arreglo de ventas con ceros reemplazados por el promedio:\n", array_ventas)


Arreglo de ventas con ceros reemplazados por el promedio:
 [1200 1537  750 2400 1537 1800]


### **Ejercicio - Análisis de Presión Arterial**
Tenemos un dataset de mediciones de presión arterial sistólica (mmHg) de 10 pacientes:
[120, 135, 140, 118, 150, 130, 160, 125, 142, 128].

Calculen:
- Media y desviación estándar.
- Identifiquen valores fuera del rango normal (90–140 mmHg).

In [53]:
array_pa = np.array([120, 135, 140, 118, 150, 130, 160, 125, 142, 128])

media_pa = np.mean(array_pa) #primedio
desviacion_pa = np.std(array_pa) #desviación estándar

print(f"Media de presión arterial: {media_pa:.2f} mmHg")
print(f"Desviación estándar: {desviacion_pa:.2f} mmHg")


# Rangos normales de presión arterial
limite_inferior = 90
limite_superior = 140

# Ubicar valores fuera del rango normal
valores_fuera_rango = array_pa[(array_pa < limite_inferior) | (array_pa > limite_superior)]


print("\nValores fuera del rango normal (90–140 mmHg):", valores_fuera_rango)

Media de presión arterial: 134.80 mmHg
Desviación estándar: 12.69 mmHg

Valores fuera del rango normal (90–140 mmHg): [150 160 142]


### **Ejercicio - Cálculo del PIB per Cápita**
Dados el PIB (en millones de USD) [500, 320, 700, 450] y la población (en millones) [10, 8, 12, 9] de 4 países, calculen el PIB per cápita y determinen el país con el mayor valor.

In [65]:
pib = np.array([500, 320, 700, 450]) # millones de USD
poblacion = np.array([10, 8, 12, 9]) #millones de personas

pib_per_capita = pib / poblacion  # División elemento a elemento del array pib/ array poblacion


print("El PIB per cápita de cada país (en miles de USD) es de:\n", pib_per_capita)

# índice del país con mayor PIB per cápita
indice_mayor = np.argmax(pib_per_capita) # argmax nos da el índice del valor máximo en el array
# ya que el indice empieza en 0, le sumamos 1 
print(f"\n\nEl país con el mayor PIB per cápita es el país #{indice_mayor + 1} con un valor de {pib_per_capita[indice_mayor]:.2f} millones de USD.")


El PIB per cápita de cada país (en miles de USD) es de:
 [50.         40.         58.33333333 50.        ]


El país con el mayor PIB per cápita es el país #3 con un valor de 58.33 millones de USD.


### **Ejercicio - Sistema de Drops (Probabilidades)**
En un videojuego RPG, los enemigos al ser vencidos, pueden dropear (soltar):
- 0 = Nada (50%).
- 1 = Poción (30%).
- 2 = Arma (15%).
- 3 = Artefacto (5%).

Simula 100 drops y cuenta cuántos artefactos se obtuvieron.

*Ejemplo de salida*:

```
Artifactos obtenidos: 3
```



In [69]:
tipos_drop = np.array([0, 1, 2, 3])

proba_drop = np.array([0.5, 0.3, 0.15, 0.05])

# usamos random.choice para simular las probabilidades de cada tipo de drop
array_drops = np.random.choice(tipos_drop, size=100, p=proba_drop)

cantidad_artefactos = np.sum(array_drops == 3) #sumamos los elementos que son iguales a 3


print(f"Artefactos obtenidos: {cantidad_artefactos}")


Artefactos obtenidos: 4
